### ISSUE TITLE
Cannot remove duplicate authors in database

### ISSUE THREAD

**Issue by eramod** [simoleone/git-coauthor#2]
I have a couple of authors listed multiple times when I run `git coauthor --ls` to see them, but when I run `git coauthor --rm <name to remove>` I get this message "warning: coauthor.author has multiple values" and it doesn't remove the user from the list. 

I also uninstalled and reinstalled the package to try to reset the list of authors, but that didn't reset it.

**Comment by simoleone** [comment]
Thanks for the report! I can have a fix for this out soon.

**Comment by simoleone** [comment]
Hey @eramod , this should be fixed in v1.2 now. You should be able to upgrade with `brew upgrade simoleone/tap/git-coauthor`.
