### ISSUE TITLE
Brew install fail

### ISSUE THREAD

**Issue by fearoffish** [simoleone/git-coauthor#4]
Hey, I'm not sure you still support this but I thought I'd try it out and received this error:

```
$ brew install simoleone/tap/git-coauthor
Error: simoleone/tap/git-coauthor: wrong number of arguments (given 1, expected 0)
```

**Comment by simoleone** [comment]
Hey! Glad someone finds it useful! 😬 I'll take a look when I get a chance, probably tomorrow.

**Comment by simoleone** [comment]
Ok should be fixed in https://github.com/simoleone/homebrew-tap/commit/4f43828699aeaaf542436174fc81f15443e53a7b

You might have to `untap` to persuade homebrew to re-pull the tap, but should work now.

```
brew untap simoleone/tap
brew install simoleone/tap/git-coauthor
```
